#!/usr/bin/env bash
# Cycle through wallpapers and update hyprpaper + rofi

set -euo pipefail

WALLPAPER_DIR="$HOME/.config/backgrounds"
STATE_FILE="$HOME/.cache/wallpaper-index"
ROFI_BG_FILE="$HOME/.config/rofi/background.rasi"

mkdir -p "$(dirname "$STATE_FILE")"

mapfile -t WALLPAPERS < <(find -L "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" -o -iname "*.jxl" \) | sort)

if [[ ${#WALLPAPERS[@]} -eq 0 ]]; then
    echo "No wallpapers found in $WALLPAPER_DIR" >&2
    exit 1
fi

# Read current index (default to 0 if file doesn't exist)
if [[ -f "$STATE_FILE" ]]; then
    CURRENT_INDEX=$(cat "$STATE_FILE")
    if ! [[ "$CURRENT_INDEX" =~ ^[0-9]+$ ]]; then
        CURRENT_INDEX=0
    fi
else
    CURRENT_INDEX=0
fi


NEXT_INDEX=$(( (CURRENT_INDEX + 1) % ${#WALLPAPERS[@]} ))
WALLPAPER="${WALLPAPERS[$CURRENT_INDEX]}"

hyprctl hyprpaper preload "$WALLPAPER"
hyprctl hyprpaper wallpaper ", $WALLPAPER"

# Update rofi background config (only targets imagebox element)
cat > "$ROFI_BG_FILE" << EOF
/* Auto-generated by change-wallpaper.sh - Do not edit manually */
imagebox {
    background-image: url("$WALLPAPER", height);
}
EOF


echo "$NEXT_INDEX" > "$STATE_FILE"
echo "Wallpaper changed to: $(basename "$WALLPAPER")"
